# Generated by Django 4.2.25 on 2025-10-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userRegistration",
            "0002_userprofile_approved_at_userprofile_approved_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="security_answer_hash",
            field=models.CharField(
                blank=True, help_text="Hashed security answer", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="security_question",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pet", "What was the name of your first pet?"),
                    ("city", "What city were you born in?"),
                    ("school", "What was the name of your elementary school?"),
                    ("teacher", "What was your favorite teacher's name?"),
                    ("food", "What is your favorite food?"),
                    ("book", "What is your favorite book?"),
                    (
                        "childhood_friend",
                        "What was the name of your childhood best friend?",
                    ),
                    ("street", "What street did you grow up on?"),
                ],
                max_length=50,
            ),
        ),
    ]
