# Generated by Django 4.2.25 on 2025-11-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userRegistration", "0004_userprofile_security_question_custom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="notes",
            field=models.CharField(
                blank=True,
                help_text="Additional information about the user (max 50 characters)",
                max_length=50,
            ),
        ),
    ]
