# Generated by Django 4.2.25 on 2025-11-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userRegistration", "0005_alter_userprofile_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="slack_member_id",
            field=models.CharField(
                blank=True,
                help_text="Slack member ID (e.g., U01234ABCD) for DM notifications",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="notes",
            field=models.CharField(
                blank=True,
                help_text="Additional information about the user (max 500 characters)",
                max_length=500,
            ),
        ),
    ]
