# Generated by Django 4.2.25 on 2025-11-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userRegistration", "0007_userprofile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="department_other",
            field=models.CharField(
                blank=True, help_text="Custom department name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="organization",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("uark", "University of Arkansas, Fayetteville"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="organization_other",
            field=models.CharField(
                blank=True, help_text="Custom organization name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("physics", "Physics"),
                    ("materials", "Materials Science"),
                    ("engineering", "Engineering"),
                    ("chemistry", "Chemistry"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
