# Generated by Django 4.2.25 on 2025-12-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userRegistration", "0008_userprofile_department_other_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="organization",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("montana", "Montana State University"),
                    ("uark", "University of Arkansas, Fayetteville"),
                    ("vtech", "Virginia Tech"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
