# Generated by Django 4.2.25 on 2025-12-31 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userRegistration", "0009_alter_userprofile_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="developer_promoted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="developer_promoted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promoted_developers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_developer",
            field=models.BooleanField(
                default=False,
                help_text="Has developer access to feedback and analytics",
            ),
        ),
    ]
