# Generated by Django 4.2.25 on 2026-01-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userRegistration", "0010_userprofile_developer_promoted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_login_browser",
            field=models.CharField(
                blank=True, help_text="Browser from last login", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_login_device",
            field=models.CharField(
                blank=True, help_text="Device type from last login", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_login_ip",
            field=models.CharField(
                blank=True, help_text="IP address from last login", max_length=45
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_login_os",
            field=models.CharField(
                blank=True, help_text="Operating system from last login", max_length=50
            ),
        ),
    ]
