"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (for local development)
from dotenv import load_dotenv
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-kf#!#6nzs&(x*=bjel79=0!&vp2y$2lszvxj5!5*o*tl@2&i6l')

# API key for automated database backups (GitHub Actions, etc.)
BACKUP_API_KEY = os.environ.get('BACKUP_API_KEY', None)

# GitHub Configuration for accessing cloud backups
GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN', '')
GITHUB_REPO = os.environ.get('GITHUB_REPO', '')  # Format: 'username/repo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')

# CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]


# Application definition

INSTALLED_APPS = [
    "daphne",  # Must be first for Channels
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "channels",
    # Local apps
    "userRegistration",
    "calendarEditor",  # Merged calendarDisplay into this app
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "userRegistration.middleware.UserApprovalMiddleware",  # Custom middleware for user approval
    "calendarEditor.middleware.CheckReminderMiddleware",  # Check for pending checkout reminders
    "calendarEditor.middleware.RenderUsageMiddleware",  # Track Render usage
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "calendarEditor.context_processors.check_in_out_count",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"

# ASGI Application (for Django Channels)
ASGI_APPLICATION = "mysite.asgi.application"

# Channel Layers Configuration (for WebSocket real-time updates)
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')

# Cache Configuration (Django Cache Framework)
# Use Redis for caching and sessions to reduce database compute usage
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,  # seconds
            'SOCKET_TIMEOUT': 5,  # seconds
            'IGNORE_EXCEPTIONS': True,  # Don't crash app if Redis is unavailable
        }
    }
}

# Use Redis for sessions instead of database
# This eliminates database queries on EVERY request (including UptimeRobot pings)
# Reduces Neon compute from ~120 CU/month to ~2-3 CU/month
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            # Gracefully handle Redis unavailability during cold starts
            "capacity": 1500,  # Max messages in channel
            "expiry": 10,  # Message expiry in seconds
            "group_expiry": 86400,  # 24 hours
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database configuration priority:
# 1. TURSO_DATABASE_URL → Turso (SQLite edge database, NO CU limits!)
# 2. DATABASE_URL → PostgreSQL (Neon, Supabase, etc.)
# 3. Default → Local SQLite (development)

turso_database_url = os.environ.get('TURSO_DATABASE_URL')
turso_auth_token = os.environ.get('TURSO_AUTH_TOKEN')
database_url = os.environ.get('DATABASE_URL')

if turso_database_url and turso_auth_token:
    # Production: Use Turso (SQLite edge database with NO CU limits!)
    # Turso uses libSQL protocol - requires custom connection handling

    print(f"🔵 Turso configuration detected:")
    print(f"   URL: {turso_database_url}")
    print(f"   Token: {'*' * 20}...{turso_auth_token[-10:] if len(turso_auth_token) > 10 else '***'}")

    # Import libsql for Turso connection
    try:
        import libsql_client

        # Create Turso client for manual queries if needed
        TURSO_CLIENT = libsql_client.create_client(
            url=turso_database_url,
            auth_token=turso_auth_token
        )

        # For Django ORM, use embedded replica approach:
        # This creates a local SQLite file that syncs with Turso
        TURSO_DB_PATH = BASE_DIR / "turso_replica.db"

        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": TURSO_DB_PATH,
                # SQLite settings optimized for production
                "OPTIONS": {
                    "timeout": 20,
                    "check_same_thread": False,  # Allow multi-threading
                },
            }
        }

        print(f"✓ Using Turso database: {turso_database_url}")

    except ImportError as e:
        print("⚠️ ERROR: libsql-client not installed!")
        print(f"   Import error: {e}")
        print("   Install with: pip install 'libsql-client>=0.3.0'")
        print("   Falling back to local SQLite...")
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }
    except Exception as e:
        print(f"⚠️ ERROR: Failed to connect to Turso: {e}")
        print("   Falling back to local SQLite...")
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }

elif database_url:
    # Check if user accidentally set DATABASE_URL to a Turso URL
    if database_url.startswith('libsql://'):
        raise ValueError(
            "❌ ERROR: DATABASE_URL contains a Turso URL (libsql://)!\n"
            "\n"
            "Use these environment variables instead:\n"
            "  TURSO_DATABASE_URL=libsql://your-db.turso.io\n"
            "  TURSO_AUTH_TOKEN=your-token-here\n"
            "\n"
            "Remove 'libsql://' from DATABASE_URL or delete DATABASE_URL entirely."
        )
    # Production: Use PostgreSQL via DATABASE_URL (Neon, Supabase, etc.)
    # Optimized for free tier: connections close immediately to allow database to sleep
    DATABASES = {
        "default": dj_database_url.parse(
            database_url,
            conn_max_age=0,  # Close connections immediately after each request (allows DB to sleep)
            conn_health_checks=True  # Verify connections before use (Django 4.1+)
        )
    }
    # Connection options compatible with pooled connections (Neon, Supabase pooler)
    DATABASES["default"]["OPTIONS"] = {
        "connect_timeout": 10,  # 10 second connection timeout
        "sslmode": "require"  # Require SSL for secure connections
    }
else:
    # Local development: SQLite in project directory
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Chicago"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Where collectstatic will collect files for production

# Static files directories
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# WhiteNoise configuration for efficient static file serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login/Logout redirects
LOGIN_URL = "login"
# LOGIN_REDIRECT_URL is overridden by CustomLoginView which redirects:
#   - Admin/staff users → admin_dashboard
#   - Regular users → home
# Fallback is "home" (never redirect to legacy "schedule" system)
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# Session configuration
# Default session age: 1 year (can be overridden by "Remember Me" checkbox in login)
SESSION_COOKIE_AGE = 31536000  # 1 year in seconds (365 days)
SESSION_SAVE_EVERY_REQUEST = True  # Reset timeout on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Persist sessions across browser restarts

# Email configuration
# For development: emails are printed to console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'scheduler@example.com'

# For production, replace with SMTP settings:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'
# DEFAULT_FROM_EMAIL = 'your-email@gmail.com'

# Celery Configuration - REMOVED
# Celery has been replaced with middleware-based reminder checking
# Reminders are now checked on every request and sent when due

# Slack Configuration
# IMPORTANT: Set SLACK_BOT_TOKEN environment variable for Slack notifications to work
# For local development, create a .env file or set in your shell
SLACK_BOT_TOKEN = os.environ.get('SLACK_BOT_TOKEN', '')
SLACK_ENABLED = bool(SLACK_BOT_TOKEN)  # Only enable if token is set

# Temperature Gateway API Configuration
# IMPORTANT: Set TEMPERATURE_GATEWAY_API_KEY for the temperature gateway script
# Generate with: python -c "import secrets; print(secrets.token_urlsafe(32))"
TEMPERATURE_GATEWAY_API_KEY = os.environ.get('TEMPERATURE_GATEWAY_API_KEY', '')

# Base URL for notification links
BASE_URL = os.environ.get('BASE_URL', 'http://127.0.0.1:8000')

# Database Storage Configuration
# Maximum database size in MB (default 500MB for Supabase free tier)
MAX_DATABASE_SIZE_MB = int(os.environ.get('MAX_DATABASE_SIZE_MB', '500'))
# Warning threshold as decimal (0.80 = 80%)
STORAGE_WARNING_THRESHOLD = 0.80
