"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (for local development)
from dotenv import load_dotenv
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-kf#!#6nzs&(x*=bjel79=0!&vp2y$2lszvxj5!5*o*tl@2&i6l')

# API key for automated database backups (GitHub Actions, etc.)
BACKUP_API_KEY = os.environ.get('BACKUP_API_KEY', None)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')

# CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]


# Application definition

INSTALLED_APPS = [
    "daphne",  # Must be first for Channels
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "channels",
    # Local apps
    "userRegistration",
    "calendarEditor",  # Merged calendarDisplay into this app
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "userRegistration.middleware.UserApprovalMiddleware",  # Custom middleware for user approval
    "calendarEditor.middleware.CheckReminderMiddleware",  # Check for pending checkout reminders
    "calendarEditor.middleware.RenderUsageMiddleware",  # Track Render usage
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "calendarEditor.context_processors.check_in_out_count",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"

# ASGI Application (for Django Channels)
ASGI_APPLICATION = "mysite.asgi.application"

# Channel Layers Configuration (for WebSocket real-time updates)
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use DATABASE_URL environment variable if available (for production)
# Otherwise use SQLite for local development
database_url = os.environ.get('DATABASE_URL')

# Check if we're on Render (RENDER env var is set automatically)
is_render = os.environ.get('RENDER') == 'true'

if database_url and not is_render:
    # External PostgreSQL/MySQL (if DATABASE_URL is set manually)
    DATABASES = {
        "default": dj_database_url.parse(database_url, conn_max_age=600)
    }
elif is_render:
    # Render: Use SQLite on persistent disk (/opt/render/project/data)
    # This avoids PostgreSQL costs while maintaining persistence
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": "/opt/render/project/data/db.sqlite3",
        }
    }
else:
    # Local development: SQLite in project directory
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Chicago"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Where collectstatic will collect files for production

# Static files directories
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# WhiteNoise configuration for efficient static file serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login/Logout redirects
LOGIN_URL = "login"
# LOGIN_REDIRECT_URL is overridden by CustomLoginView which redirects:
#   - Admin/staff users → admin_dashboard
#   - Regular users → home
# Fallback is "home" (never redirect to legacy "schedule" system)
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# Session configuration
SESSION_COOKIE_AGE = 1800  # 30 minutes in seconds
SESSION_SAVE_EVERY_REQUEST = True  # Reset timeout on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Email configuration
# For development: emails are printed to console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'scheduler@example.com'

# For production, replace with SMTP settings:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'
# DEFAULT_FROM_EMAIL = 'your-email@gmail.com'

# Celery Configuration - REMOVED
# Celery has been replaced with middleware-based reminder checking
# Reminders are now checked on every request and sent when due

# Slack Configuration
# IMPORTANT: Set SLACK_BOT_TOKEN environment variable for Slack notifications to work
# For local development, create a .env file or set in your shell
SLACK_BOT_TOKEN = os.environ.get('SLACK_BOT_TOKEN', '')
SLACK_ENABLED = bool(SLACK_BOT_TOKEN)  # Only enable if token is set

# Temperature Gateway API Configuration
# IMPORTANT: Set TEMPERATURE_GATEWAY_API_KEY for the temperature gateway script
# Generate with: python -c "import secrets; print(secrets.token_urlsafe(32))"
TEMPERATURE_GATEWAY_API_KEY = os.environ.get('TEMPERATURE_GATEWAY_API_KEY', '')

# Base URL for notification links
BASE_URL = os.environ.get('BASE_URL', 'http://127.0.0.1:8000')

# Database Storage Configuration
# Maximum database size in MB (default 1GB for Render free tier)
MAX_DATABASE_SIZE_MB = int(os.environ.get('MAX_DATABASE_SIZE_MB', '1024'))
# Warning threshold as decimal (0.80 = 80%)
STORAGE_WARNING_THRESHOLD = 0.80
