"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (for local development)
from dotenv import load_dotenv
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-kf#!#6nzs&(x*=bjel79=0!&vp2y$2lszvxj5!5*o*tl@2&i6l')

# API key for automated database backups (GitHub Actions, etc.)
BACKUP_API_KEY = os.environ.get('BACKUP_API_KEY', None)

# GitHub Configuration for accessing cloud backups
GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN', '')
GITHUB_REPO = os.environ.get('GITHUB_REPO', '')  # Format: 'username/repo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')

# CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]


# Application definition

INSTALLED_APPS = [
    "daphne",  # Must be first for Channels
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "channels",
    # Local apps
    "userRegistration",
    "calendarEditor",  # Merged calendarDisplay into this app
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",  # Compress responses (70-80% size reduction)
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "userRegistration.middleware.UserApprovalMiddleware",  # Custom middleware for user approval
    "calendarEditor.error_handling_middleware.ErrorHandlingMiddleware",  # Error handling with custom pages and developer notifications
    # "calendarEditor.middleware.ErrorLoggingMiddleware",  # DISABLED: Removed to reduce Render usage - relying on user feedback instead
    # "calendarEditor.middleware.CheckReminderMiddleware",  # DISABLED: GitHub Actions handles reminder checking via /api/check-reminders/
    "calendarEditor.middleware.RenderUsageMiddleware",  # Track Render usage
    # "calendarEditor.middleware.OnlineUserTrackingMiddleware",  # DISABLED: Reduces Render usage
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "calendarEditor.context_processors.check_in_out_count",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"

# ASGI Application (for Django Channels)
ASGI_APPLICATION = "mysite.asgi.application"

# Channel Layers Configuration (for WebSocket real-time updates)
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')

# Cache Configuration (Django Cache Framework)
# Use Redis for caching and sessions to reduce database compute usage
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,  # seconds
            'SOCKET_TIMEOUT': 5,  # seconds
            'IGNORE_EXCEPTIONS': True,  # Don't crash app if Redis is unavailable
        }
    }
}

# Use Redis for sessions instead of database
# This eliminates database queries on EVERY request (including UptimeRobot pings)
# Reduces Neon compute from ~120 CU/month to ~2-3 CU/month
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            # Gracefully handle Redis unavailability during cold starts
            "capacity": 1500,  # Max messages in channel
            "expiry": 10,  # Message expiry in seconds
            "group_expiry": 86400,  # 24 hours
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# ============================================================================
# TURSO DATABASE - NO FALLBACKS!
# ============================================================================
# This app ONLY uses Turso (SQLite edge database with NO CU limits).
# No PostgreSQL, no Neon, no local SQLite fallback.
# If Turso credentials are missing or invalid, the app will fail fast.
# ============================================================================

turso_database_url = os.environ.get('TURSO_DATABASE_URL')
turso_auth_token = os.environ.get('TURSO_AUTH_TOKEN')

if not turso_database_url or not turso_auth_token:
    raise ValueError(
        "\n"
        "❌ CRITICAL ERROR: Turso database credentials not configured!\n"
        "\n"
        "This app requires Turso database credentials. No fallback database is available.\n"
        "\n"
        "Set these environment variables:\n"
        "  TURSO_DATABASE_URL=libsql://your-db.turso.io\n"
        "  TURSO_AUTH_TOKEN=your-turso-auth-token\n"
        "\n"
        "Get your credentials from: https://turso.tech/dashboard\n"
        "  1. turso db show scheduler-db\n"
        "  2. turso db tokens create scheduler-db\n"
        "\n"
        "For local development, add to .env file:\n"
        "  TURSO_DATABASE_URL=libsql://scheduler-db-yourname.turso.io\n"
        "  TURSO_AUTH_TOKEN=eyJhbGc...\n"
    )

# Verify libsql_client is installed
try:
    import libsql_client
except ImportError:
    raise ImportError(
        "\n"
        "❌ CRITICAL ERROR: libsql-client package not installed!\n"
        "\n"
        "Install with:\n"
        "  pip install 'libsql-client>=0.3.0'\n"
        "\n"
        "Or if using requirements.txt:\n"
        "  pip install -r requirements.txt\n"
    )

print("=" * 70)
print("🔵 TURSO DATABASE CONFIGURATION")
print("=" * 70)
print(f"   URL: {turso_database_url}")
print(f"   Token: {'*' * 20}...{turso_auth_token[-10:] if len(turso_auth_token) > 10 else '***'}")
print(f"   Backend: calendarEditor.db_backends.turso")
print("=" * 70)

DATABASES = {
    "default": {
        "ENGINE": "calendarEditor.db_backends.turso",
        "TURSO_URL": turso_database_url,
        "TURSO_TOKEN": turso_auth_token,
        "NAME": ":memory:",  # Not used by Turso backend, but required by Django
    }
}

print("✅ Turso database configured successfully")

# Turso database performance settings
TURSO_QUERY_TIMEOUT = int(os.environ.get('TURSO_QUERY_TIMEOUT', 5))  # seconds
TURSO_CONNECTION_TIMEOUT = int(os.environ.get('TURSO_CONNECTION_TIMEOUT', 10))  # seconds

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Chicago"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Where collectstatic will collect files for production

# Static files directories
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# WhiteNoise configuration for efficient static file serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login/Logout redirects
LOGIN_URL = "login"
# LOGIN_REDIRECT_URL is overridden by CustomLoginView which redirects:
#   - Admin/staff users → admin_dashboard
#   - Regular users → home
# Fallback is "home" (never redirect to legacy "schedule" system)
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# Session configuration
# Default session age: 1 year (can be overridden by "Remember Me" checkbox in login)
SESSION_COOKIE_AGE = 31536000  # 1 year in seconds (365 days)
SESSION_SAVE_EVERY_REQUEST = True  # Reset timeout on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Persist sessions across browser restarts

# Email configuration
# For development: emails are printed to console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'scheduler@example.com'

# For production, replace with SMTP settings:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'
# DEFAULT_FROM_EMAIL = 'your-email@gmail.com'

# Celery Configuration - REMOVED
# Celery has been replaced with middleware-based reminder checking
# Reminders are now checked on every request and sent when due

# Slack Configuration
# IMPORTANT: Set SLACK_BOT_TOKEN environment variable for Slack notifications to work
# For local development, create a .env file or set in your shell
SLACK_BOT_TOKEN = os.environ.get('SLACK_BOT_TOKEN', '')
SLACK_ENABLED = bool(SLACK_BOT_TOKEN)  # Only enable if token is set

# Temperature Gateway API Configuration
# IMPORTANT: Set TEMPERATURE_GATEWAY_API_KEY for the temperature gateway script
# Generate with: python -c "import secrets; print(secrets.token_urlsafe(32))"
TEMPERATURE_GATEWAY_API_KEY = os.environ.get('TEMPERATURE_GATEWAY_API_KEY', '')

# Base URL for notification links
BASE_URL = os.environ.get('BASE_URL', 'http://127.0.0.1:8000')

# Database Storage Configuration
# Maximum database size in MB (default 500MB for Supabase free tier)
MAX_DATABASE_SIZE_MB = int(os.environ.get('MAX_DATABASE_SIZE_MB', '500'))
# Warning threshold as decimal (0.80 = 80%)
STORAGE_WARNING_THRESHOLD = 0.80


# Logging Configuration - Silence successful GET requests
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'skip_successful_gets': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: not (hasattr(record, 'status_code') and record.status_code == 200 and getattr(record, 'request_method', '') == 'GET')
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['skip_successful_gets'],
        },
    },
    'loggers': {
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
