# Generated by Django 4.2.25 on 2025-10-11 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calendarEditor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "min_temp",
                    models.FloatField(help_text="Minimum temperature in Kelvin"),
                ),
                (
                    "max_temp",
                    models.FloatField(help_text="Maximum temperature in Kelvin"),
                ),
                (
                    "b_field_x",
                    models.FloatField(
                        default=0, help_text="Max B-field in X direction (Tesla)"
                    ),
                ),
                (
                    "b_field_y",
                    models.FloatField(
                        default=0, help_text="Max B-field in Y direction (Tesla)"
                    ),
                ),
                (
                    "b_field_z",
                    models.FloatField(
                        default=0, help_text="Max B-field in Z direction (Tesla)"
                    ),
                ),
                (
                    "cooldown_hours",
                    models.IntegerField(help_text="Cooldown time in hours"),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("running", "Running"),
                            ("cooldown", "Cooldown"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "estimated_available_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_machine",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine",
                "verbose_name_plural": "Machines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="QueueEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Experiment title/name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Experiment description"),
                ),
                (
                    "required_min_temp",
                    models.FloatField(
                        help_text="Required minimum temperature (Kelvin)"
                    ),
                ),
                (
                    "required_max_temp",
                    models.FloatField(
                        blank=True,
                        help_text="Required maximum temperature (Kelvin, optional)",
                        null=True,
                    ),
                ),
                (
                    "required_b_field_x",
                    models.FloatField(
                        default=0, help_text="Required B-field X (Tesla)"
                    ),
                ),
                (
                    "required_b_field_y",
                    models.FloatField(
                        default=0, help_text="Required B-field Y (Tesla)"
                    ),
                ),
                (
                    "required_b_field_z",
                    models.FloatField(
                        default=0, help_text="Required B-field Z (Tesla)"
                    ),
                ),
                (
                    "estimated_duration_hours",
                    models.FloatField(help_text="Estimated duration in hours"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher number = higher priority"
                    ),
                ),
                ("queue_position", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_start_time", models.DateTimeField(blank=True, null=True)),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True, help_text="Any special requirements or notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queue_entries",
                        to="calendarEditor.machine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Entry",
                "verbose_name_plural": "Queue Entries",
                "ordering": ["assigned_machine", "queue_position", "submitted_at"],
            },
        ),
    ]
