# Generated by Django 4.2.25 on 2025-10-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0002_machine_queueentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="b_field_direction",
            field=models.CharField(
                choices=[
                    ("parallel_perpendicular", "Parallel and Perpendicular"),
                    ("perpendicular", "Perpendicular Only"),
                    ("parallel", "Parallel Only"),
                    ("none", "None"),
                ],
                default="none",
                help_text="Available B-field directions",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="daughterboard_type",
            field=models.CharField(
                blank=True,
                help_text="Daughterboard type (e.g., QBoard I, QBoard II, Montana Puck)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="dc_lines",
            field=models.IntegerField(
                default=0, help_text="Number of DC lines available"
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="optical_capabilities",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("available", "Available"),
                    ("with_work", "With Some Work"),
                    ("under_construction", "Under Construction"),
                ],
                default="none",
                help_text="Optical measurement capabilities",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="rf_lines",
            field=models.IntegerField(
                default=0, help_text="Number of RF lines available"
            ),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="required_b_field_direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No Preference"),
                    ("parallel_perpendicular", "Parallel and Perpendicular"),
                    ("perpendicular", "Perpendicular Only"),
                    ("parallel", "Parallel Only"),
                    ("none", "No B-field Needed"),
                ],
                default="",
                help_text="Required B-field direction (if any)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="required_daughterboard",
            field=models.CharField(
                blank=True,
                help_text="Required daughterboard type (leave blank for any)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="required_dc_lines",
            field=models.IntegerField(default=0, help_text="Number of DC lines needed"),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="required_rf_lines",
            field=models.IntegerField(default=0, help_text="Number of RF lines needed"),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="requires_optical",
            field=models.BooleanField(
                default=False,
                help_text="Does this experiment require optical capabilities?",
            ),
        ),
    ]
