# Generated by Django 4.2.25 on 2025-10-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calendarEditor",
            "0003_machine_b_field_direction_machine_daughterboard_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="is_rush_job",
            field=models.BooleanField(
                default=False, help_text="Is this a rush job requiring priority review?"
            ),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="rush_job_submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the rush job appeal was submitted",
                null=True,
            ),
        ),
    ]
