# Generated by Django 4.2.25 on 2025-10-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0004_queueentry_is_rush_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueentry",
            name="required_b_field_direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No Preference"),
                    ("parallel_perpendicular", "Parallel and Perpendicular"),
                    ("perpendicular", "Perpendicular Only"),
                    ("parallel", "Parallel Only"),
                ],
                default="",
                help_text="Required B-field direction (if any)",
                max_length=30,
            ),
        ),
    ]
