# Generated by Django 4.2.25 on 2025-10-20 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calendarEditor", "0005_alter_queueentry_required_b_field_direction"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueuePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-provided preset name/nickname", max_length=200
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Auto-generated formatted display name",
                        max_length=500,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Is this preset accessible to all users?",
                    ),
                ),
                ("last_edited_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.CharField(help_text="Experiment title/name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Experiment description"),
                ),
                (
                    "required_min_temp",
                    models.FloatField(
                        help_text="Required minimum temperature (Kelvin)"
                    ),
                ),
                (
                    "required_max_temp",
                    models.FloatField(
                        blank=True,
                        help_text="Required maximum temperature (Kelvin, optional)",
                        null=True,
                    ),
                ),
                (
                    "required_b_field_x",
                    models.FloatField(
                        default=0, help_text="Required B-field X (Tesla)"
                    ),
                ),
                (
                    "required_b_field_y",
                    models.FloatField(
                        default=0, help_text="Required B-field Y (Tesla)"
                    ),
                ),
                (
                    "required_b_field_z",
                    models.FloatField(
                        default=0, help_text="Required B-field Z (Tesla)"
                    ),
                ),
                (
                    "required_b_field_direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No Preference"),
                            ("parallel_perpendicular", "Parallel and Perpendicular"),
                            ("perpendicular", "Perpendicular Only"),
                            ("parallel", "Parallel Only"),
                        ],
                        default="",
                        help_text="Required B-field direction (if any)",
                        max_length=30,
                    ),
                ),
                (
                    "required_dc_lines",
                    models.IntegerField(
                        default=0, help_text="Number of DC lines needed"
                    ),
                ),
                (
                    "required_rf_lines",
                    models.IntegerField(
                        default=0, help_text="Number of RF lines needed"
                    ),
                ),
                (
                    "required_daughterboard",
                    models.CharField(
                        blank=True,
                        help_text="Required daughterboard type (leave blank for any)",
                        max_length=100,
                    ),
                ),
                (
                    "requires_optical",
                    models.BooleanField(
                        default=False,
                        help_text="Does this experiment require optical capabilities?",
                    ),
                ),
                (
                    "estimated_duration_hours",
                    models.FloatField(help_text="Estimated duration in hours"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Preset",
                "verbose_name_plural": "Queue Presets",
                "ordering": ["is_public", "name"],
            },
        ),
    ]
