# Generated by Django 4.2.25 on 2025-10-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0006_queuepreset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuepreset",
            name="estimated_duration_hours",
            field=models.FloatField(
                blank=True,
                help_text="Estimated duration in hours (optional)",
                null=True,
            ),
        ),
    ]
