# Generated by Django 4.2.25 on 2025-10-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0007_alter_queuepreset_estimated_duration_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuepreset",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Experiment description"
            ),
        ),
        migrations.AlterField(
            model_name="queuepreset",
            name="required_min_temp",
            field=models.FloatField(
                blank=True, help_text="Required minimum temperature (Kelvin)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="queuepreset",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Experiment title/name",
                max_length=200,
            ),
        ),
    ]
