# Generated by Django 4.2.25 on 2025-10-25 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calendarEditor", "0008_alter_queuepreset_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notify_public_preset_created",
                    models.BooleanField(
                        default=True, help_text="Notify when public presets are created"
                    ),
                ),
                (
                    "notify_public_preset_edited",
                    models.BooleanField(
                        default=True, help_text="Notify when public presets are edited"
                    ),
                ),
                (
                    "notify_public_preset_deleted",
                    models.BooleanField(
                        default=True, help_text="Notify when public presets are deleted"
                    ),
                ),
                (
                    "notify_private_preset_edited",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when your private presets are edited by others",
                    ),
                ),
                (
                    "notify_queue_position_change",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when your queue position changes",
                    ),
                ),
                (
                    "notify_on_deck",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when you're next in line (ON DECK)",
                    ),
                ),
                (
                    "notify_job_started",
                    models.BooleanField(
                        default=True, help_text="Notify when your job starts"
                    ),
                ),
                (
                    "notify_job_completed",
                    models.BooleanField(
                        default=True, help_text="Notify when your job completes"
                    ),
                ),
                (
                    "notify_machine_queue_changes",
                    models.BooleanField(
                        default=False,
                        help_text="Notify when entries are added to machines you're queued for",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Send notifications via email"
                    ),
                ),
                (
                    "in_app_notifications",
                    models.BooleanField(
                        default=True, help_text="Show notifications in the app"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("preset_created", "Preset Created"),
                            ("preset_edited", "Preset Edited"),
                            ("preset_deleted", "Preset Deleted"),
                            ("queue_added", "Queue Entry Added"),
                            ("queue_moved", "Queue Entry Moved"),
                            ("queue_cancelled", "Queue Entry Cancelled"),
                            ("on_deck", "On Deck - You're Next!"),
                            ("job_started", "Job Started"),
                            ("job_completed", "Job Completed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="calendarEditor.machine",
                    ),
                ),
                (
                    "related_preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="calendarEditor.queuepreset",
                    ),
                ),
                (
                    "related_queue_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="calendarEditor.queueentry",
                    ),
                ),
                (
                    "triggering_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="calendarEdi_recipie_a80f5e_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="calendarEdi_recipie_1b61dc_idx",
                    ),
                ],
            },
        ),
    ]
