# Generated by Django 4.2.25 on 2025-10-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0009_notificationpreference_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_admin_new_user",
            field=models.BooleanField(
                default=True, help_text="[Admin] Notify when new users sign up"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_admin_rush_job",
            field=models.BooleanField(
                default=True, help_text="[Admin] Notify when rush jobs are submitted"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("preset_created", "Preset Created"),
                    ("preset_edited", "Preset Edited"),
                    ("preset_deleted", "Preset Deleted"),
                    ("queue_added", "Queue Entry Added"),
                    ("queue_moved", "Queue Entry Moved"),
                    ("queue_cancelled", "Queue Entry Cancelled"),
                    ("on_deck", "On Deck - You're Next!"),
                    ("job_started", "Job Started"),
                    ("job_completed", "Job Completed"),
                    ("admin_new_user", "New User Signup"),
                    ("admin_rush_job", "Rush Job/Special Request Submitted"),
                ],
                max_length=30,
            ),
        ),
    ]
