# Generated by Django 4.2.25 on 2025-10-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0010_add_admin_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="followed_presets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Presets you're following for notifications",
                related_name="followers",
                to="calendarEditor.queuepreset",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_followed_preset_deleted",
            field=models.BooleanField(
                default=True, help_text="Notify when presets you follow are deleted"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_followed_preset_edited",
            field=models.BooleanField(
                default=True, help_text="Notify when presets you follow are edited"
            ),
        ),
    ]
