# Generated by Django 4.2.25 on 2025-10-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0011_notificationpreference_followed_presets_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="notify_followed_preset_deleted",
            field=models.BooleanField(
                default=False, help_text="Notify when presets you follow are deleted"
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notify_followed_preset_edited",
            field=models.BooleanField(
                default=False, help_text="Notify when presets you follow are edited"
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notify_job_started",
            field=models.BooleanField(
                default=False, help_text="Notify when your job starts"
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notify_public_preset_created",
            field=models.BooleanField(
                default=False, help_text="Notify when public presets are created"
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notify_public_preset_deleted",
            field=models.BooleanField(
                default=False, help_text="Notify when public presets are deleted"
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notify_public_preset_edited",
            field=models.BooleanField(
                default=False, help_text="Notify when public presets are edited"
            ),
        ),
    ]
