# Generated by Django 4.2.25 on 2025-10-27 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "calendarEditor",
            "0012_alter_notificationpreference_notify_followed_preset_deleted_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="queuepreset",
            name="creator_username",
            field=models.CharField(
                default="unknown",
                help_text="Username of the creator (preserved if user is deleted)",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="queuepreset",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_presets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
