# Generated by Django 4.2.25 on 2025-10-27 20:33

from django.db import migrations


def backfill_creator_usernames(apps, schema_editor):
    """Backfill creator_username from creator relationship for existing presets."""
    QueuePreset = apps.get_model('calendarEditor', 'QueuePreset')

    for preset in QueuePreset.objects.all():
        if preset.creator:
            preset.creator_username = preset.creator.username
            preset.save(update_fields=['creator_username'])


def reverse_backfill(apps, schema_editor):
    """Reverse migration - set all creator_usernames to 'unknown'."""
    QueuePreset = apps.get_model('calendarEditor', 'QueuePreset')
    QueuePreset.objects.all().update(creator_username='unknown')


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0013_preset_creator_username"),
    ]

    operations = [
        migrations.RunPython(backfill_creator_usernames, reverse_backfill),
    ]
