# Generated by Django 4.2.25 on 2025-10-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0014_backfill_creator_usernames"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_ready_for_check_in",
            field=models.BooleanField(
                default=True,
                help_text="Notify when the machine is available and you can check in",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("preset_created", "Preset Created"),
                    ("preset_edited", "Preset Edited"),
                    ("preset_deleted", "Preset Deleted"),
                    ("queue_added", "Queue Entry Added"),
                    ("queue_moved", "Queue Entry Moved"),
                    ("queue_cancelled", "Queue Entry Cancelled"),
                    ("on_deck", "On Deck - You're Next!"),
                    ("ready_for_check_in", "Ready for Check-In"),
                    ("job_started", "Job Running"),
                    ("job_completed", "Ready for Check-Out"),
                    ("admin_new_user", "New User Signup"),
                    ("admin_rush_job", "Rush Job/Special Request Submitted"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notify_job_completed",
            field=models.BooleanField(
                default=True,
                help_text="Notify when your estimated measurement time has elapsed and you should check out",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notify_job_started",
            field=models.BooleanField(
                default=False,
                help_text="Notify when you successfully check in and your job starts running",
            ),
        ),
    ]
