# Generated by Django 4.2.25 on 2025-10-28 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0015_add_ready_for_check_in_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(500)]
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="queueentry",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Experiment description",
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="queueentry",
            name="special_requirements",
            field=models.TextField(
                blank=True,
                help_text="Any special requirements or notes",
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="queueentry",
            name="title",
            field=models.CharField(help_text="Experiment title/name", max_length=500),
        ),
        migrations.AlterField(
            model_name="queuepreset",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Experiment description",
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="queuepreset",
            name="name",
            field=models.CharField(
                help_text="User-provided preset name/nickname", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="queuepreset",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Experiment title/name",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="description",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MaxLengthValidator(500)]
            ),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="special_requirements",
            field=models.TextField(
                blank=True,
                help_text="Any special requirements or notes",
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
