# Generated by Django 4.2.25 on 2025-10-29 00:18

import calendarEditor.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "calendarEditor",
            "0016_alter_notification_message_alter_notification_title_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measurement_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date when the measurement was taken",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the measurement",
                        max_length=500,
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this measurement",
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                (
                    "preset_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="JSON snapshot of the preset/configuration used",
                        null=True,
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded measurement data file",
                        null=True,
                        upload_to=calendarEditor.models.archived_measurement_upload_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="published",
                        help_text="Archive entry status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine",
                    models.ForeignKey(
                        help_text="Machine used for this measurement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archived_measurements",
                        to="calendarEditor.machine",
                    ),
                ),
                (
                    "related_queue_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original queue entry (if archived from queue)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_measurements",
                        to="calendarEditor.queueentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this archive entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archived_measurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived Measurement",
                "verbose_name_plural": "Archived Measurements",
                "ordering": ["-measurement_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-measurement_date"],
                        name="calendarEdi_user_id_b9ae95_idx",
                    ),
                    models.Index(
                        fields=["machine", "-measurement_date"],
                        name="calendarEdi_machine_53ffd4_idx",
                    ),
                    models.Index(
                        fields=["-measurement_date"],
                        name="calendarEdi_measure_1b30b6_idx",
                    ),
                ],
            },
        ),
    ]
