# Generated by Django 4.2.25 on 2025-10-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0017_archivedmeasurement"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="auto_archive",
            field=models.BooleanField(
                default=False,
                help_text="Automatically create an archive entry when this measurement is completed",
            ),
        ),
    ]
