# Generated by Django 4.2.25 on 2025-10-29 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0018_queueentry_auto_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmeasurement",
            name="archived_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When this entry was added to the archive",
            ),
        ),
        migrations.AlterField(
            model_name="archivedmeasurement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("archived", "Archived"),
                ],
                default="published",
                help_text="Archive entry status",
                max_length=20,
            ),
        ),
    ]
