# Generated by Django 4.2.25 on 2025-10-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0019_archivedmeasurement_archived_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="queueentry", name="auto_archive",),
    ]
