# Generated by Django 4.2.25 on 2025-11-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0021_update_notification_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("preset_created", "Preset Created"),
                    ("preset_edited", "Preset Edited"),
                    ("preset_deleted", "Preset Deleted"),
                    ("queue_added", "Queue Entry Added"),
                    ("queue_moved", "Queue Entry Moved"),
                    ("queue_cancelled", "Queue Entry Cancelled"),
                    ("on_deck", "On Deck - You're Next!"),
                    ("ready_for_check_in", "Ready for Check-In"),
                    ("checkout_reminder", "Time to Check Out"),
                    (
                        "machine_status_changed",
                        "Machine Status Changed - Time to Check Out",
                    ),
                    ("admin_check_in", "Admin Checked You In"),
                    ("admin_checkout", "Admin Checked You Out"),
                    ("admin_new_user", "New User Signup"),
                    ("admin_rush_job", "Rush Job Submitted"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="queueentry",
            name="title",
            field=models.CharField(help_text="Experiment title/name", max_length=75),
        ),
        migrations.AlterField(
            model_name="queuepreset",
            name="name",
            field=models.CharField(
                help_text="User-provided preset name/nickname", max_length=75
            ),
        ),
        migrations.AlterField(
            model_name="queuepreset",
            name="title",
            field=models.CharField(
                blank=True, default="", help_text="Experiment title/name", max_length=75
            ),
        ),
    ]
