# Generated by Django 4.2.25 on 2025-11-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0022_alter_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_admin_check_in",
            field=models.BooleanField(
                default=True, help_text="Notify when an admin checks you in"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_admin_checkout",
            field=models.BooleanField(
                default=True, help_text="Notify when an admin checks you out"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_machine_status_change",
            field=models.BooleanField(
                default=True,
                help_text="Notify when admin changes machine status affecting your measurement",
            ),
        ),
    ]
