# Generated by Django 4.2.25 on 2025-11-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0024_onetimelogintoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_admin_edit_entry",
            field=models.BooleanField(
                default=True, help_text="Notify when an admin edits your queue entry"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("preset_created", "Preset Created"),
                    ("preset_edited", "Preset Edited"),
                    ("preset_deleted", "Preset Deleted"),
                    ("queue_added", "Queue Entry Added"),
                    ("queue_moved", "Queue Entry Moved"),
                    ("queue_cancelled", "Queue Entry Cancelled"),
                    ("on_deck", "On Deck - You're Next!"),
                    ("ready_for_check_in", "Ready for Check-In"),
                    ("checkout_reminder", "Time to Check Out"),
                    (
                        "machine_status_changed",
                        "Machine Status Changed - Time to Check Out",
                    ),
                    ("admin_check_in", "Admin Checked You In"),
                    ("admin_checkout", "Admin Checked You Out"),
                    ("admin_edit_entry", "Admin Edited Your Entry"),
                    ("admin_new_user", "New User Signup"),
                    ("admin_rush_job", "Rush Job Submitted"),
                ],
                max_length=30,
            ),
        ),
    ]
