# Generated by Django 4.2.25 on 2025-11-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calendarEditor",
            "0025_notificationpreference_notify_admin_edit_entry_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="api_port",
            field=models.IntegerField(
                blank=True,
                help_text="API port (e.g., 47101 for Quantum Design)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="api_type",
            field=models.CharField(
                choices=[
                    ("port5001", "Port 5001 (Hidalgo/Griffin)"),
                    ("quantum_design", "Quantum Design (OptiCool/CryoCore)"),
                    ("none", "No API"),
                ],
                default="none",
                help_text="Type of temperature API",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="ip_address",
            field=models.CharField(
                blank=True,
                help_text="IP address for temperature monitoring",
                max_length=15,
            ),
        ),
    ]
