# Generated by Django 4.2.25 on 2025-11-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0026_machine_api_port_machine_api_type_machine_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="cached_online",
            field=models.BooleanField(
                default=True, help_text="Cached online/offline status"
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="cached_temperature",
            field=models.FloatField(
                blank=True, help_text="Cached temperature reading in Kelvin", null=True
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="last_temp_update",
            field=models.DateTimeField(
                blank=True, help_text="Last time temperature was updated", null=True
            ),
        ),
    ]
