# Generated by Django 4.2.25 on 2025-11-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calendarEditor",
            "0027_machine_cached_online_machine_cached_temperature_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="reminder_due_at",
            field=models.DateTimeField(
                blank=True, help_text="When checkout reminder should be sent", null=True
            ),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="reminder_sent",
            field=models.BooleanField(
                default=False, help_text="Whether checkout reminder was sent"
            ),
        ),
    ]
