# Generated by Django 4.2.25 on 2025-11-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0030_add_orphaned_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="machine_name_text",
            field=models.CharField(
                blank=True,
                help_text="Machine name as text (preserved after machine deletion)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("preset_created", "Preset Created"),
                    ("preset_edited", "Preset Edited"),
                    ("preset_deleted", "Preset Deleted"),
                    ("queue_added", "Queue Entry Added"),
                    ("queue_moved", "Queue Entry Moved"),
                    ("queue_cancelled", "Queue Entry Cancelled"),
                    ("on_deck", "On Deck - You're Next!"),
                    ("ready_for_check_in", "Ready for Check-In"),
                    ("checkout_reminder", "Time to Check Out"),
                    (
                        "machine_status_changed",
                        "Machine Status Changed - Time to Check Out",
                    ),
                    ("admin_check_in", "Admin Checked You In"),
                    ("admin_checkout", "Admin Checked You Out"),
                    ("admin_edit_entry", "Admin Edited Your Entry"),
                    ("admin_moved_entry", "Admin Moved Your Queue Entry"),
                    ("account_approved", "Account Approved"),
                    ("account_unapproved", "Account Unapproved"),
                    ("account_promoted", "Promoted to Staff"),
                    ("account_demoted", "Demoted from Staff"),
                    ("account_info_changed", "Account Information Changed"),
                    ("admin_new_user", "New User Signup"),
                    ("admin_rush_job", "Rush Job Submitted"),
                ],
                max_length=30,
            ),
        ),
    ]
