# Generated by Django 4.2.25 on 2025-11-19 14:07

from django.db import migrations, models


def set_default_duration(apps, schema_editor):
    """Set default duration of 1 hour for existing archived measurements."""
    ArchivedMeasurement = apps.get_model("calendarEditor", "ArchivedMeasurement")
    ArchivedMeasurement.objects.filter(duration_hours__isnull=True).update(duration_hours=1.0)


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0031_queueentry_machine_name_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmeasurement",
            name="duration_hours",
            field=models.FloatField(
                blank=True, help_text="Duration of measurement in hours", null=True
            ),
        ),
        migrations.RunPython(set_default_duration, reverse_code=migrations.RunPython.noop),
    ]
