# Generated by Django 4.2.25 on 2025-11-19 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0032_archivedmeasurement_duration_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueentry",
            name="description",
            field=models.TextField(
                help_text="Experiment description",
                validators=[
                    django.core.validators.MinLengthValidator(50),
                    django.core.validators.MaxLengthValidator(500),
                ],
            ),
        ),
    ]
