# Generated by Django 4.2.25 on 2025-11-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calendarEditor",
            "0033_alter_queueentry_description",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queueentry",
            name="reminder_sent",
        ),
        migrations.AddField(
            model_name="queueentry",
            name="last_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the last checkout reminder was sent (for repeat reminders every 2 hours)",
                null=True,
            ),
        ),
    ]
