# Generated by Django 4.2.25 on 2025-11-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calendarEditor",
            "0034_replace_reminder_sent_with_timestamp",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="reminder_snoozed_until",
            field=models.DateTimeField(
                blank=True,
                help_text="When the reminder snooze expires (user clicked notification link)",
                null=True,
            ),
        ),
    ]
