# Generated by Django 4.2.25 on 2025-11-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calendarEditor",
            "0035_add_reminder_snooze_field",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="checkin_reminder_due_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When check-in reminder should be sent (for ON DECK entries)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="last_checkin_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the last check-in reminder was sent (for repeat reminders every 6 hours)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="checkin_reminder_snoozed_until",
            field=models.DateTimeField(
                blank=True,
                help_text="When the check-in reminder snooze expires (user clicked notification link)",
                null=True,
            ),
        ),
    ]
