# Generated by Django 4.2.25 on 2025-11-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0036_add_checkin_reminder_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_account_approved",
            field=models.BooleanField(
                default=True,
                help_text="Notify when your account is approved - CRITICAL",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_account_demoted",
            field=models.BooleanField(
                default=True,
                help_text="Notify when you're demoted from staff - CRITICAL",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_account_info_changed",
            field=models.BooleanField(
                default=True,
                help_text="Notify when your account information is changed - CRITICAL",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_account_promoted",
            field=models.BooleanField(
                default=True,
                help_text="Notify when you're promoted to staff - CRITICAL",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_account_unapproved",
            field=models.BooleanField(
                default=True,
                help_text="Notify when your account is unapproved - CRITICAL",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_admin_moved_entry",
            field=models.BooleanField(
                default=True, help_text="Notify when an admin moves your queue entry"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_checkin_reminder",
            field=models.BooleanField(
                default=True, help_text="Notify when you forget to check in - CRITICAL"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_database_restored",
            field=models.BooleanField(
                default=True,
                help_text="[Admin] Notify when database is restored - CRITICAL",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_queue_added",
            field=models.BooleanField(
                default=True,
                help_text="Notify when your queue entry is successfully added",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_queue_cancelled",
            field=models.BooleanField(
                default=True, help_text="Notify when your queue entry is cancelled"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("preset_created", "Preset Created"),
                    ("preset_edited", "Preset Edited"),
                    ("preset_deleted", "Preset Deleted"),
                    ("queue_added", "Queue Entry Added"),
                    ("queue_moved", "Queue Entry Moved"),
                    ("queue_cancelled", "Queue Entry Cancelled"),
                    ("on_deck", "On Deck - You're Next!"),
                    ("ready_for_check_in", "Ready for Check-In"),
                    ("checkin_reminder", "Did You Forget to Check In?"),
                    ("checkout_reminder", "Time to Check Out"),
                    (
                        "machine_status_changed",
                        "Machine Status Changed - Time to Check Out",
                    ),
                    ("admin_check_in", "Admin Checked You In"),
                    ("admin_checkout", "Admin Checked You Out"),
                    ("admin_edit_entry", "Admin Edited Your Entry"),
                    ("admin_moved_entry", "Admin Moved Your Queue Entry"),
                    ("account_approved", "Account Approved"),
                    ("account_unapproved", "Account Unapproved"),
                    ("account_promoted", "Promoted to Staff"),
                    ("account_demoted", "Demoted from Staff"),
                    ("account_info_changed", "Account Information Changed"),
                    ("admin_new_user", "New User Signup"),
                    ("admin_rush_job", "Rush Job/Special Request Submitted"),
                    ("database_restored", "Database Restored"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notify_admin_new_user",
            field=models.BooleanField(
                default=True,
                help_text="[Admin] Notify when new users sign up - CRITICAL",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notify_admin_rush_job",
            field=models.BooleanField(
                default=True,
                help_text="[Admin] Notify when rush jobs are submitted - CRITICAL",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notify_checkout_reminder",
            field=models.BooleanField(
                default=True,
                help_text="Notify when your estimated measurement time has elapsed and you should check out - CRITICAL",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notify_on_deck",
            field=models.BooleanField(
                default=True,
                help_text="Notify when you're next in line (ON DECK) - CRITICAL",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notify_ready_for_check_in",
            field=models.BooleanField(
                default=True,
                help_text="Notify when the machine is available and you can check in - CRITICAL",
            ),
        ),
        migrations.AlterField(
            model_name="queueentry",
            name="reminder_snoozed_until",
            field=models.DateTimeField(
                blank=True,
                help_text="When the checkout reminder snooze expires (user clicked notification link)",
                null=True,
            ),
        ),
    ]
