# Generated by Django 4.2.25 on 2025-12-31 03:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "calendarEditor",
            "0037_notificationpreference_notify_account_approved_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueentry",
            name="last_checkin_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the last check-in reminder was sent (for repeat reminders every 12 hours)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="queueentry",
            name="last_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the last checkout reminder was sent (for repeat reminders every 12 hours)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="queueentry",
            name="machine_name_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Machine name as text (preserved after machine deletion)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="queueentry",
            name="required_daughterboard",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Required daughterboard type (leave blank for any)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="queueentry",
            name="special_requirements",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Any special requirements or notes",
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="queuepreset",
            name="required_daughterboard",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Required daughterboard type (leave blank for any)",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("click", "Click"),
                            ("form_submit", "Form Submit"),
                            ("queue_submit", "Queue Submit"),
                            ("check_in", "Check In"),
                            ("check_out", "Check Out"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        help_text="What was clicked/submitted", max_length=200
                    ),
                ),
                ("page_path", models.CharField(max_length=500)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="calendarEdi_created_d4da4d_idx"
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="calendarEdi_action__b166d5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("path", models.CharField(max_length=500)),
                ("page_title", models.CharField(blank=True, max_length=200)),
                ("referrer", models.CharField(blank=True, max_length=500)),
                ("device_info", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Page View",
                "verbose_name_plural": "Page Views",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="calendarEdi_created_f80123_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="calendarEdi_user_id_3f5b52_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug Report"),
                            ("feature", "Feature Request"),
                            ("opinion", "Opinion/Suggestion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief summary of feedback", max_length=150
                    ),
                ),
                ("description", models.TextField(help_text="Detailed description")),
                (
                    "replication_steps",
                    models.TextField(blank=True, help_text="Steps to reproduce bug"),
                ),
                (
                    "console_logs",
                    models.TextField(blank=True, help_text="F12 console logs"),
                ),
                (
                    "device_info",
                    models.JSONField(
                        default=dict, help_text="Browser, OS, device type"
                    ),
                ),
                (
                    "user_level",
                    models.CharField(
                        help_text="user/staff/developer/admin at submission time",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("completed", "Completed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "developer_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes from developers"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="calendarEdi_status_ff817d_idx",
                    ),
                    models.Index(
                        fields=["feedback_type", "status"],
                        name="calendarEdi_feedbac_7ab770_idx",
                    ),
                ],
            },
        ),
    ]
