# Generated by Django 4.2.25 on 2025-12-31 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "calendarEditor",
            "0038_alter_queueentry_last_checkin_reminder_sent_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("404", "404 Not Found"),
                            ("500", "500 Server Error"),
                            ("403", "403 Forbidden"),
                            ("400", "400 Bad Request"),
                            ("exception", "Unhandled Exception"),
                        ],
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.IntegerField()),
                ("error_message", models.TextField(blank=True)),
                ("stack_trace", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Log",
                "verbose_name_plural": "Error Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="calendarEdi_created_f0dc0e_idx"
                    ),
                    models.Index(
                        fields=["error_type", "-created_at"],
                        name="calendarEdi_error_t_ff61ef_idx",
                    ),
                    models.Index(
                        fields=["status_code", "-created_at"],
                        name="calendarEdi_status__dc5677_idx",
                    ),
                ],
            },
        ),
    ]
