# Generated by Django 4.2.25 on 2026-01-01 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0039_errorlog"),
    ]

    operations = [
        migrations.RunSQL(
            # Add column with default value
            sql="ALTER TABLE calendarEditor_queueentry ADD COLUMN requested_measurement_days INTEGER NOT NULL DEFAULT 2;",
            # Reverse migration - remove the column
            reverse_sql="ALTER TABLE calendarEditor_queueentry DROP COLUMN requested_measurement_days;",
        ),
    ]
