# Generated by Django 4.2.25 on 2026-01-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0040_auto_20251231_2011"),
    ]

    operations = [
        # Add warmup_hours column
        migrations.RunSQL(
            sql="ALTER TABLE calendarEditor_machine ADD COLUMN warmup_hours INTEGER NOT NULL DEFAULT 0;",
            reverse_sql="ALTER TABLE calendarEditor_machine DROP COLUMN warmup_hours;",
        ),
        # Set warmup times for each machine
        migrations.RunSQL(
            sql="""
                UPDATE calendarEditor_machine SET warmup_hours = 3 WHERE name = 'Griffin';
                UPDATE calendarEditor_machine SET warmup_hours = 3 WHERE name = 'Hidalgo';
                UPDATE calendarEditor_machine SET warmup_hours = 4 WHERE name = 'CryoCore';
                UPDATE calendarEditor_machine SET warmup_hours = 12 WHERE name = 'OptiCool';
                UPDATE calendarEditor_machine SET warmup_hours = 1 WHERE name = 'Kiutra';
            """,
            reverse_sql="UPDATE calendarEditor_machine SET warmup_hours = 0;",
        ),
    ]
