# Generated by Django 4.2.25 on 2026-01-01 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0041_add_machine_warmup_hours"),
    ]

    operations = [
        # Add requested_measurement_days to QueuePreset model
        migrations.RunSQL(
            sql="ALTER TABLE calendarEditor_queuepreset ADD COLUMN requested_measurement_days INTEGER NOT NULL DEFAULT 2;",
            reverse_sql="ALTER TABLE calendarEditor_queuepreset DROP COLUMN requested_measurement_days;",
        ),
    ]
