# Generated by Django 4.2.25 on 2026-01-02 00:01

from django.db import migrations, models


def rename_optical_values(apps, schema_editor):
    """Update existing machines with old optical_capabilities values to new shortened values."""
    Machine = apps.get_model('calendarEditor', 'Machine')

    # Map old values to new values
    value_mapping = {
        'optical_setup_not_working': 'optical_not_working',
        'optical_ICE_motherboard_Qboard_1': 'ice_mb_qb1',
    }

    for old_value, new_value in value_mapping.items():
        Machine.objects.filter(optical_capabilities=old_value).update(optical_capabilities=new_value)


def reverse_rename_optical_values(apps, schema_editor):
    """Reverse the renaming (for rollback)."""
    Machine = apps.get_model('calendarEditor', 'Machine')

    # Reverse mapping
    value_mapping = {
        'optical_not_working': 'optical_setup_not_working',
        'ice_mb_qb1': 'optical_ICE_motherboard_Qboard_1',
    }

    for new_value, old_value in value_mapping.items():
        Machine.objects.filter(optical_capabilities=new_value).update(optical_capabilities=old_value)


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0042_add_preset_measurement_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="warmup_hours",
            field=models.IntegerField(
                default=0, help_text="Warmup/heatup time in hours"
            ),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="requested_measurement_days",
            field=models.IntegerField(
                default=2,
                help_text="Requested time on machine for measurements (1-7 days)",
            ),
        ),
        migrations.AddField(
            model_name="queuepreset",
            name="requested_measurement_days",
            field=models.IntegerField(
                default=2,
                help_text="Requested time on machine for measurements (1-7 days)",
            ),
        ),
        migrations.RunPython(rename_optical_values, reverse_rename_optical_values),
        migrations.AlterField(
            model_name="machine",
            name="optical_capabilities",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("available", "Available"),
                    ("optical_not_working", "Optical Setup (Not Working)"),
                    ("ice_mb_qb1", "Optical ICE Motherboard Qboard 1"),
                    ("under_construction", "Under Construction"),
                    ("with_work", "With Some Work"),
                ],
                default="none",
                help_text="Optical measurement capabilities",
                max_length=30,
            ),
        ),
    ]
