# Generated by Django 4.2.25 on 2026-01-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0043_rename_optical_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_appeal_approved",
            field=models.BooleanField(
                default=True,
                help_text="Notify when your queue appeal is approved - CRITICAL",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_appeal_rejected",
            field=models.BooleanField(
                default=True,
                help_text="Notify when your queue appeal is rejected - CRITICAL",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_developer_feedback",
            field=models.BooleanField(
                default=True,
                help_text="[Developer] Notify when users submit feedback - CRITICAL",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="slack_notifications",
            field=models.BooleanField(
                default=True, help_text="Send notifications via Slack direct messages"
            ),
        ),
    ]
