# Generated by Django 4.2.25 on 2026-01-03 14:36

from django.db import migrations


def add_columns_if_not_exist(apps, schema_editor):
    """Add notification preference columns using raw SQL to avoid table recreation."""
    with schema_editor.connection.cursor() as cursor:
        # Check if columns exist and add them if they don't
        try:
            cursor.execute("""
                ALTER TABLE calendarEditor_notificationpreference
                ADD COLUMN notify_appeal_approved INTEGER DEFAULT 1 NOT NULL
            """)
        except Exception as e:
            # Column likely already exists
            print(f"notify_appeal_approved column might already exist: {e}")

        try:
            cursor.execute("""
                ALTER TABLE calendarEditor_notificationpreference
                ADD COLUMN notify_appeal_rejected INTEGER DEFAULT 1 NOT NULL
            """)
        except Exception as e:
            print(f"notify_appeal_rejected column might already exist: {e}")

        try:
            cursor.execute("""
                ALTER TABLE calendarEditor_notificationpreference
                ADD COLUMN notify_developer_feedback INTEGER DEFAULT 1 NOT NULL
            """)
        except Exception as e:
            print(f"notify_developer_feedback column might already exist: {e}")

        try:
            cursor.execute("""
                ALTER TABLE calendarEditor_notificationpreference
                ADD COLUMN slack_notifications INTEGER DEFAULT 1 NOT NULL
            """)
        except Exception as e:
            print(f"slack_notifications column might already exist: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0044_add_appeal_and_developer_notification_preferences"),
    ]

    operations = [
        migrations.RunPython(add_columns_if_not_exist, migrations.RunPython.noop),
    ]
