# Generated by Django 4.2.25 on 2026-01-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendarEditor", "0045_add_notification_columns_manually"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_appeal_response",
            field=models.BooleanField(
                default=True,
                help_text="Notify when you receive a response to your appeal - CRITICAL",
            ),
        ),
        migrations.AddField(
            model_name="queuepreset",
            name="selected_optical_machine",
            field=models.ForeignKey(
                blank=True,
                help_text="Machine selected for optical measurements (if requires_optical is True)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preset_optical_selections",
                to="calendarEditor.machine",
            ),
        ),
    ]
