# Generated by Django 4.2.25 on 2026-05-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calendarEditor",
            "0046_notificationpreference_notify_appeal_response_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "calendarEditor_queueentry" ADD COLUMN "requires_temp_dependence" bool NOT NULL DEFAULT 0;',
            reverse_sql='ALTER TABLE "calendarEditor_queueentry" DROP COLUMN "requires_temp_dependence";',
            state_operations=[
                migrations.AddField(
                    model_name="queueentry",
                    name="requires_temp_dependence",
                    field=models.BooleanField(
                        default=False,
                        help_text="Does this experiment require temperature dependent measurements above dilution fridge capability?",
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "calendarEditor_queuepreset" ADD COLUMN "requires_temp_dependence" bool NOT NULL DEFAULT 0;',
            reverse_sql='ALTER TABLE "calendarEditor_queuepreset" DROP COLUMN "requires_temp_dependence";',
            state_operations=[
                migrations.AddField(
                    model_name="queuepreset",
                    name="requires_temp_dependence",
                    field=models.BooleanField(
                        default=False,
                        help_text="Does this experiment require temperature dependent measurements above dilution fridge capability?",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="machine",
            name="daughterboard_type",
            field=models.CharField(
                blank=True,
                help_text="Daughterboard type (e.g., QBoard I, QBoard II, Montana Puck, DIP)",
                max_length=100,
            ),
        ),
    ]
