# Generated by Django 4.2.25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calendarEditor", "0048_trainingupdaterequest_and_training_notifications"),
    ]

    operations = [
        # --- Appeal reminder tracking (nullable DateTimeFields - safe as plain AddField,
        #     same shape as 0036_add_checkin_reminder_fields.py) ---
        migrations.AddField(
            model_name="queueentry",
            name="appeal_reminder_due_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When the first 'appeal still unreviewed' nag should be sent",
            ),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="last_appeal_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When the last 24-hour appeal reminder was sent",
            ),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="appeal_clicked_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When appeal_clicked_by first clicked the reminder link",
            ),
        ),
        migrations.AddField(
            model_name="queueentry",
            name="last_appeal_escalation_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When the last hourly escalation was sent",
            ),
        ),
        # --- Nullable FK (safe as plain AddField, same shape as 0046's selected_optical_machine) ---
        migrations.AddField(
            model_name="queueentry",
            name="appeal_clicked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clicked_appeal_reminders",
                to=settings.AUTH_USER_MODEL,
                help_text="Admin who first clicked an appeal reminder link for this entry",
            ),
        ),
        # --- Click tracking primitive on OneTimeLoginToken ---
        migrations.AddField(
            model_name="onetimelogintoken",
            name="first_accessed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When this link was first opened (click tracking; the token itself remains reusable)",
            ),
        ),
        # --- NOT NULL BooleanField with default - use RunSQL + state_operations,
        #     matching the established safe pattern from 0047/0048 for this field shape ---
        migrations.RunSQL(
            sql='ALTER TABLE "calendarEditor_notificationpreference" ADD COLUMN "notify_admin_appeal_shame" bool NOT NULL DEFAULT 1;',
            reverse_sql='ALTER TABLE "calendarEditor_notificationpreference" DROP COLUMN "notify_admin_appeal_shame";',
            state_operations=[
                migrations.AddField(
                    model_name="notificationpreference",
                    name="notify_admin_appeal_shame",
                    field=models.BooleanField(
                        default=True,
                        help_text="[Admin] Notify hourly when a clicked-but-unreviewed appeal is still pending - CRITICAL",
                    ),
                ),
            ],
        ),
        # --- Choices-only metadata change, no schema impact (same shape as 0022) ---
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("preset_created", "Preset Created"),
                    ("preset_edited", "Preset Edited"),
                    ("preset_deleted", "Preset Deleted"),
                    ("queue_added", "Queue Entry Added"),
                    ("queue_moved", "Queue Entry Moved"),
                    ("queue_cancelled", "Queue Entry Cancelled"),
                    ("on_deck", "On Deck - You're Next!"),
                    ("ready_for_check_in", "Ready for Check-In"),
                    ("checkin_reminder", "Did You Forget to Check In?"),
                    ("checkout_reminder", "Time to Check Out"),
                    (
                        "machine_status_changed",
                        "Machine Status Changed - Time to Check Out",
                    ),
                    ("admin_check_in", "Admin Checked You In"),
                    ("admin_checkout", "Admin Checked You Out"),
                    ("admin_edit_entry", "Admin Edited Your Entry"),
                    ("admin_moved_entry", "Admin Moved Your Queue Entry"),
                    ("account_approved", "Account Approved"),
                    ("account_unapproved", "Account Unapproved"),
                    ("account_promoted", "Promoted to Staff"),
                    ("account_demoted", "Demoted from Staff"),
                    ("account_info_changed", "Account Information Changed"),
                    ("admin_new_user", "New User Signup"),
                    ("admin_rush_job", "Rush Job/Special Request Submitted"),
                    ("admin_rush_job_reminder", "Queue Appeal Still Unreviewed"),
                    ("admin_rush_job_escalation", "Queue Appeal Shame Escalation"),
                    ("database_restored", "Database Restored"),
                    ("training_request", "Training Update Requested"),
                    ("training_approved", "Training Request Approved"),
                    ("training_rejected", "Training Request Rejected"),
                ],
                max_length=30,
            ),
        ),
    ]
